{% set name = "jupyter_events" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: faff25f77218335752f35f23c5fe6e4a392a7bd99a5939ccb9b8fbf594636cf3

build:
  number: 0
  skip: True # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - jupyter-events = jupyter_events.cli:main

requirements:
  host:
    - pip
    - python
    - hatchling >=1.5
  run:
    - python
    - jsonschema >=4.18.0
    - traitlets >=5.3
    - pyyaml >=5.3
    - rfc3339-validator
    - rfc3986-validator >=0.1.1
    - referencing
    - python-json-logger >=2.0.4
    - packaging

test:
  source_files:
    - tests
  imports:
    - jupyter_events
  requires:
    - pip
    - pytest >=7.0
    - pytest-asyncio >=0.19.0
    - pytest-tornasync
    - pytest-console-scripts
    - click
    - rich
  commands:
    - pip check
    - python -m pytest --ignore=tests/test_cli.py -v
    - jupyter-events --help

about:
  home: https://pypi.org/project/jupyter-events
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Event System library
  description: Jupyter Events enables Jupyter Python Applications (e.g. Jupyter Server, JupyterLab Server, JupyterHub, etc.) to emit events—structured data describing things happening inside the application. Other software (e.g. client applications like JupyterLab) can listen and respond to these events.
  dev_url: https://github.com/jupyter/jupyter_events
  doc_url: https://jupyter-events.readthedocs.io

extra:
  recipe-maintainers:
    - Zsailer
    - blink1073
    - afshin
