{% set name = "jupyter_events" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_events-{{ version }}.tar.gz
  sha256: e27ffdd6138699d47d42cb65ae6d79334ff7c0d923694381c991ce56a140f2cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.0
  run:
    - jsonschema >=4.3
    - python >=3.7
    - python-json-logger >=2.0.4
    - traitlets >=5.3
    - pyyaml >=6.0

test:
  source_files:
    - .
  imports:
    - jupyter_events
  commands:
    - pip check
    - pip install -e ".[test]"
    - python -m pytest -vv
  requires:
    - pip

about:
  home: https://pypi.org/project/jupyter-events/
  dev_url: https://github.com/jupyter/jupyter_events
  summary: Jupyter Event System library
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md

extra:
  recipe-maintainers:
    - Zsailer
    - blink1073
    - afshin
