{% set name = "jupyter_events" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_events-{{ version }}.tar.gz
  sha256: 0fc2567f3cefbce8da40c0fa2c8214d0c51140a99a157c78ddd63ef0f1b38b4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.0
  run:
    - jsonschema
    - python >=3.7
    - python-json-logger
    - ruamel.yaml
    - traitlets

test:
  imports:
    - jupyter_events
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jupyter-events/
  dev_url: https://github.com/jupyter/jupyter_events
  summary: Jupyter Event System library
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md

extra:
  recipe-maintainers:
    - Zsailer
    - blink1073
    - afshin
