{% set name = "jupyter_events" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_events-{{ version }}.tar.gz
  sha256: 9a6e9995f75d1b7146b436ea24d696ce3a35bfa8bfe45e0c33c334c79464d0b3 

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: True # [py <37]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.5
    - wheel
  run:
    - jsonschema >=3.2
    - python
    - python-json-logger >=2.0.4
    - traitlets >=5.3
    - pyyaml >=5.3
    - rfc3339-validator
    - rfc3986-validator >=0.1.1

test:
  source_files:
    - tests
  imports:
    - jupyter_events
  requires:
    - pip
    - pytest >=7.0
    - click
    - rich
    - anyio
  commands:
    - pip check
    - python -m pytest -k "not (test_listeners.py or test_cli.py or test_noop_emit)" -vv

about:
  home: https://pypi.org/project/jupyter-events/
  dev_url: https://github.com/jupyter/jupyter_events
  summary: Jupyter Event System library
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  description: Jupyter Events enables Jupyter Python Applications (e.g. Jupyter Server, JupyterLab Server, JupyterHub, etc.) to emit events—structured data describing things happening inside the application. Other software (e.g. client applications like JupyterLab) can listen and respond to these events.
  doc_url: https://jupyter-events.readthedocs.io

extra:
  recipe-maintainers:
    - Zsailer
    - blink1073
    - afshin
